version: "3"
services:
  cvs_vax_finder:
    container_name: cvs_vax_finder
    build:
      context: .
      dockerfile: Dockerfile
    network_mode: "container:wireguard"
    env_file: '.env'
    command: "npm start"
